/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ShowIndexLazyImport = createFileRoute('/show/')()
const ShowIdIndexLazyImport = createFileRoute('/show/$id/')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ShowIndexLazyRoute = ShowIndexLazyImport.update({
  path: '/show/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/show/index.lazy').then((d) => d.Route))

const ShowIdIndexLazyRoute = ShowIdIndexLazyImport.update({
  path: '/show/$id/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/show/$id/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/show/': {
      id: '/show/'
      path: '/show'
      fullPath: '/show'
      preLoaderRoute: typeof ShowIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/show/$id/': {
      id: '/show/$id/'
      path: '/show/$id'
      fullPath: '/show/$id'
      preLoaderRoute: typeof ShowIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ShowIndexLazyRoute,
  ShowIdIndexLazyRoute,
})

/* prettier-ignore-end */
